#!/bin/sh

[ -f /etc/sysconfig/clamd ] && . /etc/sysconfig/clamd

[ -z "$FETCH_AFTER_UPGRADE" ] && FETCH_AFTER_UPGRADE="no"

if [ "$FETCH_AFTER_UPGRADE" = "yes" ]; then
	if [ "$UPDATE_QUIET" = "yes" ]; then
		freshclamopt="--quiet"
	fi

	notify=
	[ -f /var/lock/subsys/clamd ] && notify="--daemon-notify"

	umask 022
	/usr/bin/freshclam $freshclamopt -l /var/log/freshclam.log $notify || :
fi
